PROCESS_STEPS = [
    {"id": "1.1", "name": "Review of Cargo Nominations", "highlighted": True},
    {"id": "1.2", "name": "Ship Adaptability", "highlighted": False},
    {"id": "1.3", "name": "SAFE Acceptability", "highlighted": True},
    {"id": "1.4", "name": "Previous Cargo?", "highlighted": False},
    {"id": "1.5", "name": "Stowage Plan", "highlighted": False},
    {"id": "1.6", "name": "STAR Risk Assessment", "highlighted": True},
    {"id": "2.1", "name": "Check DEX Entries and FED Contracts", "highlighted": True},
    {"id": "2.2", "name": "Financial Securities", "highlighted": False},
    {"id": "2.3", "name": "Identify Terms of Deals (CIF/FOB)", "highlighted": True},
    {"id": "2.4", "name": "Assign Ship", "highlighted": False},
    {"id": "2.5", "name": "Nominate to the Terminal", "highlighted": False},
    {"id": "2.6", "name": "Update DEX & RADAR", "highlighted": True},
    {"id": "2.7", "name": "Send Voyage Orders", "highlighted": False},
    {"id": "2.8", "name": "Agency Nomination", "highlighted": False},
    {"id": "2.9", "name": "Documentation Instructions", "highlighted": True},
    {"id": "2.10", "name": "Inspection Nomination", "highlighted": False},
    {"id": "2.11", "name": "Ship Updates - ETA, ETB, ETC", "highlighted": True},
    {"id": "2.12", "name": "Bunkering Requirements", "highlighted": False},
    {"id": "3.1", "name": "Coordination with Agent on Berth Schedule", "highlighted": False},
    {"id": "3.2", "name": "Possible Port Requirements", "highlighted": False},
    {"id": "3.3", "name": "Coordination with Trader on Berth Schedule", "highlighted": False},
    {"id": "3.4", "name": "Marine LOI Requirements", "highlighted": True},
    {"id": "4.1", "name": "Ensure Documents Onboard", "highlighted": False},
    {"id": "4.2", "name": "Advise Next Destination", "highlighted": False},
    {"id": "4.3", "name": "Check Cargo Quantity Loaded", "highlighted": False},
    {"id": "4.4", "name": "Update DEX for BL Quantity", "highlighted": True},
    {"id": "4.5", "name": "Review Cargo Quality", "highlighted": True},
    {"id": "4.6", "name": "EDP", "highlighted": True},
    {"id": "5.1", "name": "ETA Update", "highlighted": False},
    {"id": "5.2", "name": "Marine LOI Requirements", "highlighted": False},
    {"id": "5.3", "name": "Coordination with Agents and Ship", "highlighted": False},
    {"id": "5.4", "name": "Documents Received?", "highlighted": True},
    {"id": "6.1", "name": "Coordination with Agent on Berth Schedule", "highlighted": False},
    {"id": "6.2", "name": "Confirmation of Receiver to Discharge", "highlighted": False},
    {"id": "7.1", "name": "Check Cargo Discharged", "highlighted": False},
    {"id": "7.2", "name": "DEX Update", "highlighted": True},
    {"id": "7.3", "name": "RADAR Update", "highlighted": True},
    {"id": "8.1", "name": "Claims & Loss Reporting", "highlighted": False},
    {"id": "8.2", "name": "Payment of Freight & Oil Charges", "highlighted": False},
    {"id": "8.3", "name": "Invoicing for Freight and Oil Claims", "highlighted": False},
    {"id": "8.4", "name": "Payment of Inspection", "highlighted": False},
    {"id": "8.5", "name": "Import/Export Permit", "highlighted": False},
]